@deliveries = http://localhost:5000
@orders = http://localhost:5001
@pricing = http://localhost:5002
@client = vip

###
POST {{orders}}/orders
Content-Type: application/json

{
  "client": "{{client}}"
}

###
GET {{pricing}}/clients/{{client}}/discount
